apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: server-container
        imagePullPolicy: Always
        image: alexsaavedraa/DOCKERIMAGE:v6 # Replace with your actual image name and tag
        ports:
        - containerPort: 8080  # Port exposed by the client container
      - name: postgres
        imagePullPolicy: Always
        image: alexsaavedraa/postgres:v1 # Replace with your actual image name and tag
        ports:
        
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: go-server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    targetPort: 8080  # Port exposed by the client container
 

