apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
        - name: server-container
          image:  22172d7f4893 # Replace with your actual image name and tag
          imagePullPolicy: Always
          ports:
            - containerPort: 8292  # Port exposed by the Go server container (updated to 8292)
        - name: postgres
          image: 7592e667be0a  # Replace with your actual image name and tag
          imagePullPolicy: Always
          ports:
            - containerPort: 5432  # Port exposed by the PostgreSQL container

---

        
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: go-server
  ports:
    - name: https
      port: 443
      targetPort: 8292  # Targeting port 8292 of the container (Go server)